services:
  - type: web
    name: ecomanage
    env: node
    region: singapore
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build && cd ../backend && npm install && cp -r ../frontend/dist ./public
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGOMS_DISABLE_POSTINSTALL
        value: 1
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
